name: common
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  package_info_plus: ^8.1.1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.3
  currency_text_input_formatter: ^2.2.6
  money_formatter: ^0.0.6
  dropdown_button2: ^2.3.9
  shimmer: ^3.0.0
  flutter_inappwebview: ^6.1.5
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.3.1
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_flavorizr: ^2.2.3
  talker_dio_logger: ^4.4.7

flutter:
  uses-material-design: true

  assets:
    - lib/common/assets/images/logos/social_media/
    - lib/common/assets/images/logos/banks_logo/
    - lib/common/assets/images/logos/services/
    - lib/common/assets/images/chinchin/
 